#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(std140, binding = 3) buffer buffer0 {
  vec4 values0[];
};

layout(std140, binding = 4) buffer buffer1 {
  vec4 values1[];
};

void main()
{
  if (gl_GlobalInvocationID.x >= 128 || gl_GlobalInvocationID.y >= 128)
    return;

  uint index = gl_GlobalInvocationID.y + gl_GlobalInvocationID.x * 128;
  values1[index] = values0[index] + 0.01;
}
